### PR TITLE
Implement isempty function

### PR DESCRIPTION
**Pull request by asmeurer**
`idx.isempty()` returns True if `idx` always indexes to an empty array. 

It still needs tests

### CODE REVIEW

**Comment by asmeurer** [comment]
This is ready for review.

**Comment by scopatz** [comment]
Looks like there is a CI error

**Comment by asmeurer** [comment]
Yeah, just some coverage issues. I always forget to check the full test suite locally. This should be good now.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
