### PR TITLE
Raise NotImplementedError for ndindex(list)

### PR DESCRIPTION
**Pull request by asmeurer**

### CODE REVIEW

**Comment by scopatz** [comment]
Would this be easy to add a test for?

**Comment by asmeurer** [comment]
I don't generally test for NotImplemenedErrors.

**Comment by asmeurer** [comment]
The test failure here is a random failure, which is already fixed in https://github.com/Quansight/ndindex/pull/57.

**Comment by scopatz** [comment]
Thanks for adding the test anyway!

**Pull request merged**
