### PR TITLE
Implement IntegerArray

### LINKED ISSUE #25: Implement IntegerArray
An integer array does fancy indexing. See https://numpy.org/devdocs/reference/arrays.indexing.html#advanced-indexing.

### PR DESCRIPTION
**Pull request by asmeurer**
Fixes #25.

### CODE REVIEW

**Comment by asmeurer** [comment]
OK, there's a weird corner case in integer array indexing that currently fails the tests here. Integer indices on empty arrays sometimes do not give out of bounds IndexErrors. NumPy is deprecating this behavior, but the deprecation won't be live until 1.20 (https://github.com/numpy/numpy/pull/15900). 

I would like to make ndindex follow any post-deprecation warning behavior for NumPy, since that leads to a cleaner API. But it will not be straightforward to tests against this until 1.20 is released. I don't know how often NumPy does major releases. If it comes around that everything else here is ready except for that, I will just code in the 1.19 behavior and update it later.

**Comment by melissawm** [comment]
FYI, the 1.20 release for NumPy is about 6 months away.

**Comment by asmeurer** [comment]
Thanks. I didn't know there was a schedule. For now I have just emulated 1.19 behavior. I will update it once 1.20 is out, which will be a minor compatibility break, but I think it isn't a big deal.

**Comment by asmeurer** [comment]
I think it would be good to review and merge this as it is. There are still a lot of things that aren't yet implemented, like as_subindex for IntegerArray, and Tuples of IntegerArrays, but those will be more work and it might be cleaner to do them as separate PRs.

**Pull request merged**
