### PR TITLE
Add support for Slice and Tuple.as_subindex(Integer)

### PR DESCRIPTION
**Pull request by asmeurer**
This still needs tests.

### CODE REVIEW

**Comment by asmeurer** [comment]
The failures are caused by a numpy update. I will fix in another PR.

**Comment by asmeurer** [comment]
This is ready for review. The test failures should go away once https://github.com/Quansight/ndindex/pull/59 is merged.

**Comment by melissawm** [comment]
Not sure if @scopatz wants to take a look, as far as I can see this can be merged.

**Comment by scopatz** [comment]
Seems like there are conflicts

**Comment by asmeurer** [comment]
I've fixed the conflicts.

**Pull request merged**
